# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tntapp.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tntapp.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_de_cursado', models.IntegerField(default=1)),
                ('lugar_de_dictado', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('id_calendario', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='asistencia',
            name='id_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tntapp.Materia'),
        ),
        migrations.AddField(
            model_name='alumnomateria',
            name='id_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tntapp.Materia'),
        ),
    ]
