# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnomateria',
            name='id_alumno',
        ),
        migrations.RemoveField(
            model_name='alumnomateria',
            name='id_materia',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='latitud',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='longitud',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='id_alumno',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='AlumnoMateria',
        ),
    ]
