# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0005_materia_ts_actualizacion_eventos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMateria',
            fields=[
                ('id_evento', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('comienzo', models.CharField(max_length=80, null=True)),
                ('fin', models.CharField(max_length=80, null=True)),
                ('direccion', models.CharField(max_length=80, null=True)),
                ('titulo', models.CharField(max_length=80, null=True)),
                ('descrip', models.CharField(max_length=80, null=True)),
                ('se_repite', models.BooleanField()),
                ('ts_last_modified', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='materia',
            name='ts_actualizacion_eventos',
        ),
        migrations.AddField(
            model_name='eventomateria',
            name='id_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tntapp.Materia'),
        ),
    ]
