# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tntapp', '0006_auto_20160704_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventomateria',
            old_name='id_materia',
            new_name='materia',
        ),
    ]
